"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMPORT_SCENARIO_ROUTE = exports.TEXT_TO_ORBAT_ROUTE = exports.MAP_EDIT_MODE_ROUTE = exports.CHART_EDIT_MODE_ROUTE = exports.GRID_EDIT_ROUTE = exports.ORBAT_CHART_ROUTE = exports.STORY_MODE_ROUTE = exports.LANDING_PAGE_ROUTE = exports.NEW_SCENARIO_ROUTE = exports.OLD_MAP_ROUTE = void 0;
exports.OLD_MAP_ROUTE = "ScenarioRoute";
exports.NEW_SCENARIO_ROUTE = "NewScenarioRoute";
exports.LANDING_PAGE_ROUTE = "LandingPageRoute";
exports.STORY_MODE_ROUTE = "StoryModeRoute";
exports.ORBAT_CHART_ROUTE = "OrbatChartRoute";
exports.GRID_EDIT_ROUTE = "GridEditRoute";
exports.CHART_EDIT_MODE_ROUTE = "ChartModeRoute";
exports.MAP_EDIT_MODE_ROUTE = "MapBetaModeRoute";
exports.TEXT_TO_ORBAT_ROUTE = "TextToOrbatRoute";
exports.IMPORT_SCENARIO_ROUTE = "ImportScenarioRoute";
