"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.activeFeatureSelectInteractionKey = exports.activeMapKey = exports.searchActionsKey = exports.sidcModalKey = exports.timeModalKey = exports.currentScenarioTabKey = exports.activeFeatureStylesKey = exports.activeScenarioKey = exports.activeLayerKey = exports.activeParentKey = void 0;
exports.activeParentKey = Symbol("Active unit");
exports.activeLayerKey = Symbol("Active layer");
exports.activeScenarioKey = Symbol("Active scenario");
exports.activeFeatureStylesKey = Symbol("Active feature styles");
exports.currentScenarioTabKey = Symbol("Current scenario tab");
exports.timeModalKey = Symbol("Time modal");
exports.sidcModalKey = Symbol("SIDC modal");
exports.searchActionsKey = Symbol("Search actions");
exports.activeMapKey = Symbol("Active map");
exports.activeFeatureSelectInteractionKey = Symbol("Active feature select");
